micronaut:
  application:
    name: bugReport1
datasources:
  default:
    url: jdbc:h2:mem:devDb;INIT=runscript from './src/main/resources/schema.sql'
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
