micronaut:
  application:
    name: bugReport1
datasources:
  default:
    url: jdbc:h2:mem:br1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
